# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.3, generator: @autorest/powershell@4.0.722)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------
Write-Host -ForegroundColor Green 'Packing module...'
dotnet pack $PSScriptRoot --no-build /nologo
Write-Host -ForegroundColor Green '-------------Done-------------'